# Shared common data.
data:
  image: debian
  volumes:
    - ./data/common/:/data/common/

# An example mysql resource.
mysql:
  image: mysql
  volumes:
    - ./data/mysql/:/var/lib/mysql/
  environment:
    MYSQL_ROOT_PASSWORD: root

# An example python app
python:
  build: ./python
  volumes:
    - ./python/src/:/app
  volumes_from:
    - data
  working_dir: /app
  environment:
    PYTHONUNBUFFERED: 1
  #links:
  # Uncomment to link to mysql
  #  - mysql:mysql
  command: python main.py

# An example flask app
flask:
  build: ./flask
  volumes_from:
    - data
  volumes:
    - ./flask/src/:/app
  working_dir: /app
  environment:
    PYTHONUNBUFFERED: 1
  ports:
    - 3000:80
  # Uncomment to link to mysql
  #links:
  #  - mysql:mysql
  command: python server.py
