# An example mysql resource.
mysql:
  image: mysql
  volumes:
    - ./db/mysql/:/var/lib/mysql/
  environment:
    MYSQL_ROOT_PASSWORD: root

# An example python app
python:
  build: ./python
  volumes:
    - ./python/src/:/app
  working_dir: /app
  environment:
    PYTHONUNBUFFERED: 1
  # Uncomment to link to mysql
  #links:
  #  - mysql:mysql
  command: python main.py

# An example flask app
flask:
  build: ./flask
  volumes:
    - ./flask/src/:/app
  working_dir: /app
  environment:
    PYTHONUNBUFFERED: 1
  ports:
    - 3000:80
  # Uncomment to link to mysql
  #links:
  #  - mysql:mysql
  command: python server.py
